# Generated by Django 5.0.2 on 2024-06-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstructorRegModel",
            fields=[
                ("instructor_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=55)),
                ("email", models.EmailField(help_text="Enter Email", max_length=100)),
                ("phone_number", models.BigIntegerField(null=True)),
                ("gender", models.CharField(default=False, max_length=50)),
                (
                    "password",
                    models.CharField(help_text="Enter Password", max_length=100),
                ),
                ("photo", models.ImageField(default=False, upload_to="")),
                (
                    "status",
                    models.CharField(default="Pending", max_length=100, null=True),
                ),
                ("reg_date", models.DateField(auto_now_add=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("otp", models.CharField(default=0, max_length=6)),
                ("otp_status", models.CharField(default="Not Verified", max_length=15)),
            ],
            options={
                "db_table": "Instructor_Details",
            },
        ),
        migrations.CreateModel(
            name="Addcourse",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                ("course_image", models.ImageField(upload_to="course_images/")),
                ("course_category", models.CharField(max_length=100)),
                ("course_language", models.CharField(max_length=100)),
                ("course_description", models.TextField()),
                ("video_url", models.URLField()),
                ("duration_weeks", models.IntegerField()),
                ("price", models.IntegerField(default=0, help_text="Enter fee ")),
                ("added_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.instructorregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "Courses_details",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.addcourse",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.instructorregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "Questions",
            },
        ),
    ]
