# Generated by Django 5.0.2 on 2024-06-21 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addcourse",
            name="price",
        ),
    ]
