# Generated by Django 5.0.2 on 2024-06-21 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0002_remove_addcourse_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addcourse",
            name="instructor",
        ),
    ]
