# Generated by Django 5.0.2 on 2024-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0003_remove_addcourse_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addcourse",
            name="course_description",
        ),
    ]
