# Generated by Django 5.0.2 on 2024-06-21 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0004_remove_addcourse_course_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="instructor",
        ),
    ]
