# Generated by Django 5.0.2 on 2024-06-21 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0005_remove_question_instructor"),
        ("userapp", "0004_remove_cartmodel_cart_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="course",
        ),
        migrations.DeleteModel(
            name="InstructorRegModel",
        ),
        migrations.DeleteModel(
            name="Addcourse",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
