# Generated by Django 5.0.2 on 2024-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0007_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholarshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=100)),
                ("grade_level", models.CharField(max_length=10)),
                ("parent_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("scholarship_category", models.CharField(max_length=100)),
                ("proof_of_enrollment", models.FileField(upload_to="proofs/")),
                ("essay", models.TextField()),
            ],
            options={
                "db_table": "scholarshi",
            },
        ),
    ]
