# Generated by Django 5.0.2 on 2024-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0008_scholarshipapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("parent_name", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=100)),
                ("grade_level", models.CharField(max_length=10)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("parent_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("proof_of_enrollment", models.FileField(upload_to="proofs/")),
                ("bank_account", models.CharField(max_length=50)),
                ("loan_purpose", models.TextField()),
                ("additional_info", models.TextField(blank=True)),
            ],
            options={
                "db_table": "loan",
            },
        ),
    ]
