# Generated by Django 5.0.2 on 2024-06-22 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0013_initial"),
        ("userapp", "0010_remove_cartmodel_cart_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="course",
        ),
        migrations.DeleteModel(
            name="InstructorRegModel",
        ),
        migrations.DeleteModel(
            name="LoanApplication",
        ),
        migrations.DeleteModel(
            name="ScholarshipApplication",
        ),
        migrations.DeleteModel(
            name="Addcourse",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
