# Generated by Django 5.0.2 on 2024-06-23 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0015_initial"),
        ("userapp", "0012_remove_cartmodel_cart_booking_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Addcourse",
        ),
        migrations.DeleteModel(
            name="InstructorRegModel",
        ),
        migrations.DeleteModel(
            name="LoanApplication",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="ScholarshipApplication",
        ),
    ]
