# Generated by Django 5.0.2 on 2024-06-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminapp", "0015_initial"),
        ("userapp", "0010_remove_cartmodel_cart_booking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultModel",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("test_id", models.IntegerField(null=True)),
                ("test_name", models.CharField(max_length=155)),
                ("question", models.CharField(max_length=155)),
                ("useranswer", models.CharField(max_length=55)),
                ("correctanswer", models.CharField(max_length=55)),
                ("marks", models.IntegerField()),
                ("result_date", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "Student_Result_Details",
            },
        ),
        migrations.CreateModel(
            name="StudentRegModel",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "full_name",
                    models.CharField(
                        help_text="Enter full Name", max_length=100, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter Email Address", max_length=100, null=True
                    ),
                ),
                ("phone_number", models.BigIntegerField()),
                (
                    "photo",
                    models.ImageField(default="image", null=True, upload_to="images/"),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Enter Password", max_length=10, null=True
                    ),
                ),
                ("reg_date", models.DateField(auto_now_add=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("otp", models.CharField(default=0, max_length=6)),
                ("otp_status", models.CharField(default="Not Verified", max_length=15)),
                (
                    "class_selected",
                    models.CharField(
                        choices=[
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "db_table": "Student_Details",
            },
        ),
        migrations.CreateModel(
            name="StudentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("rating", models.IntegerField()),
                ("additional_comments", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.studentregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "student_feedback",
            },
        ),
        migrations.CreateModel(
            name="StudentCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0, help_text="Enter fee")),
                ("payment_status", models.CharField(default="pending", max_length=100)),
                ("purchase_date", models.DateField(auto_now_add=True, null=True)),
                ("payment_id", models.CharField(max_length=200)),
                ("order_id", models.CharField(max_length=200)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminapp.addcourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_courses",
                        to="userapp.studentregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "student_courses_details",
            },
        ),
        migrations.CreateModel(
            name="CartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.addcourse",
                    ),
                ),
                (
                    "cart_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.studentregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "cart_details",
            },
        ),
        migrations.CreateModel(
            name="UserTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=155, unique=True)),
                ("test_date", models.DateField(auto_now_add=True)),
                ("test_marks", models.IntegerField(default=0)),
                (
                    "test_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_results",
                        to="userapp.studentregmodel",
                    ),
                ),
            ],
            options={
                "db_table": "User_tests_details",
            },
        ),
    ]
